In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../Data/raw_messy_data.csv')

In [3]:
df.head(10)

,economy,Country,year,gdp_per_capita,gdp_growth,fdi_inflows,unemployment,poverty_headcount,gini_index,life_expectancy,...,renewable_energy,forest_area,clean_water_access,female_labour,female_literacy,women_parliament,maternal_mortality,gender_parity,internet_users,sub_region
0,AFG,Afghanistan,YR2000,174.930991,NaN,0.004828,7.897,NaN,NaN,55.005,...,45.0,1.852782,29.730966,14.294,NaN,NaN,1372.0,NaN,NaN,South Asia
1,AFG,Afghanistan,YR2001,138.706822,-9.431974,0.024169,7.973,NaN,NaN,55.511,...,45.6,1.852782,29.762926,14.196,NaN,NaN,1311.0,0.00000,0.004723,South Asia
2,AFG,Afghanistan,YR2002,178.954088,28.600001,1.306950,7.867,NaN,NaN,56.225,...,37.8,1.852782,31.836077,14.152,NaN,NaN,1263.0,NaN,0.004561,South Asia
3,AFG,Afghanistan,YR2003,198.871116,8.832278,1.278493,7.844,NaN,NaN,57.171,...,36.7,1.852782,33.908629,14.154,NaN,NaN,1201.0,0.54426,0.087891,South Asia
4,AFG,Afghanistan,YR2004,221.763654,1.414118,3.577104,7.794,NaN,NaN,57.810,...,44.2,1.852782,35.999355,14.205,NaN,NaN,1166.0,0.40582,0.105809,South Asia
5,AFG,Afghanistan,YR2005,254.184249,11.229715,4.368673,7.878,NaN,NaN,58.247,...,33.9,1.852782,38.108054,14.302,NaN,27.309237,1108.0,0.54769,1.224150,South Asia
6,AFG,Afghanistan,YR2006,274.218554,5.357403,3.413773,7.897,NaN,NaN,58.553,...,31.9,1.852782,40.215763,14.452,NaN,27.309237,1069.0,0.57323,2.107120,South Asia
7,AFG,Afghanistan,YR2007,376.223152,13.826320,1.935702,7.841,NaN,NaN,58.956,...,28.8,1.852782,42.429496,14.670,NaN,27.685950,1032.0,0.56720,1.900000,South Asia
8,AFG,Afghanistan,YR2008,381.733238,3.924984,0.455360,7.879,NaN,NaN,59.708,...,21.2,1.852782,44.653792,14.944,NaN,27.685950,955.0,0.58602,1.840000,South Asia
9,AFG,Afghanistan,YR2009,452.053705,21.390528,0.451889,7.808,NaN,NaN,60.248,...,16.5,1.852782,46.888584,15.248,NaN,27.309237,925.0,0.60961,3.550000,South Asia

In [4]:
df.shape

(1128, 28)

In [5]:
df.describe()

,gdp_per_capita,gdp_growth,fdi_inflows,unemployment,poverty_headcount,gini_index,life_expectancy,infant_mortality,hospital_beds,population,...,electricity_access,renewable_energy,forest_area,clean_water_access,female_labour,female_literacy,women_parliament,maternal_mortality,gender_parity,internet_users
count,1098.000000,1097.000000,1079.000000,1127.000000,363.000000,363.000000,1128.000000,1128.000000,966.000000,1.128000e+03,...,1119.000000,1038.000000,1128.000000,1124.000000,1127.000000,329.000000,1035.000000,1128.000000,637.000000,1077.000000
mean,10879.168971,4.771827,3.758433,6.272689,11.375758,35.203857,72.173427,23.999734,3.055476,9.049645e+07,...,89.764790,20.588825,23.858503,89.506265,43.035464,83.623582,14.589999,103.105496,0.972462,37.073420
std,16444.309719,6.103189,5.668861,4.876761,16.353972,4.904732,5.859500,19.829006,2.702960,2.626202e+08,...,19.024478,25.464837,24.304753,12.975554,18.735034,18.309649,9.328634,166.144698,0.100575,32.568198
min,136.925716,-36.656780,-37.172653,0.100000,0.000000,25.100000,55.005000,1.700000,0.200000,2.820190e+05,...,4.400000,0.000000,0.000000,29.730966,4.752000,17.020000,0.000000,2.000000,0.000000,0.000000
25%,1220.249354,2.490949,0.737073,3.067500,0.700000,31.500000,67.921500,8.700000,1.340000,4.401090e+06,...,89.250000,1.000000,2.733333,86.130707,26.594000,76.800003,6.574145,18.000000,0.966490,6.758850
50%,3578.411232,5.045124,2.185494,4.693000,3.400000,35.300000,72.430000,18.000000,2.170000,1.704637e+07,...,99.600000,7.000000,12.655911,94.015199,47.236000,91.500000,14.473684,39.000000,0.998330,26.900000
75%,11382.938567,7.328374,4.708120,8.553500,16.500000,38.800000,76.278250,33.625000,4.047500,5.081373e+07,...,100.000000,34.800000,41.590722,98.834708,57.178000,95.919998,21.138211,121.250000,1.021440,66.484600
max,108470.387023,58.078101,55.072877,27.465000,93.800000,47.700000,84.560000,110.100000,14.670000,1.438070e+09,...,100.000000,92.000000,75.498267,100.000000,81.841000,100.000000,50.000000,1372.000000,1.145880,100.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 28 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   economy                     1128 non-null   object
 1   Country                     1128 non-null   object
 2   year                        1128 non-null   object
 3   gdp_per_capita              1098 non-null   float64
 4   gdp_growth                  1097 non-null   float64
 5   fdi_inflows                 1079 non-null   float64
 6   unemployment                1127 non-null   float64
 7   poverty_headcount           363 non-null    float64
 8   gini_index                  363 non-null    float64
 9   life_expectancy             1128 non-null   float64
 10  infant_mortality            1128 non-null   float64
 11  hospital_beds               966 non-null    float64
 12  population                  1128 non-null   float64
 13  literacy_rate               324 non-null    float64
 14  school_enrolment_primary    930 non-null    float64
 15  school_enrolment_secondary  820 non-null    float64
 16  education_expenditure       727 non-null    float64
 17  electricity_access          1119 non-null   float64
 18  renewable_energy            1038 non-null   float64
 19  forest_area                 1128 non-null   float64
 20  clean_water_access          1124 non-null   float64
 21  female_labour               1127 non-null   float64
 22  female_literacy             329 non-null    float64
 23  women_parliament            1035 non-null   float64
 24  maternal_mortality          1128 non-null   float64
 25  gender_parity               637 non-null    float64
 26  internet_users              1077 non-null   float64
 27  sub_region                  1128 non-null   object
dtypes: float64(24), object(4)
memory usage: 246.9+ KB

In [7]:
df['year']=df["year"].str.lstrip('YR').astype(int)

In [8]:
df['gdp_per_capita'].isnull().sum()

np.int64(30)

In [9]:
(df['gdp_per_capita']<0).sum()

np.int64(0)

In [10]:
df.groupby('Country')['gdp_per_capita'].count()

Country
Afghanistan                  24
Armenia                      24
Azerbaijan                   24
Bahrain                      24
Bangladesh                   24
Bhutan                       24
Brunei Darussalam            24
Cambodia                     24
China                        24
Georgia                      24
India                        24
Indonesia                    24
Iran, Islamic Rep.           24
Iraq                         24
Israel                       24
Japan                        24
Jordan                       24
Kazakhstan                   24
Korea, Dem. People's Rep.     0
Korea, Rep.                  24
Kuwait                       24
Kyrgyz Republic              24
Lao PDR                      24
Lebanon                      24
Malaysia                     24
Maldives                     24
Mongolia                     24
Myanmar                      24
Nepal                        24
Oman                         24
Pakistan                     24
Philippines                  24
Qatar                        24
Saudi Arabia                 24
Singapore                    24
Sri Lanka                    24
Syrian Arab Republic         23
Tajikistan                   24
Thailand                     24
Timor-Leste                  24
Turkiye                      24
Turkmenistan                 24
United Arab Emirates         24
Uzbekistan                   24
Viet Nam                     24
West Bank and Gaza           24
Yemen, Rep.                  19
Name: gdp_per_capita, dtype: int64

In [11]:
df.drop(df[df['Country'] =="Korea, Dem. People's Rep."].index,inplace=True)

In [12]:
df['gdp_per_capita']=df.groupby('Country')['gdp_per_capita'].transform(lambda x : x.fillna(x.median()))

In [13]:
df['gdp_per_capita'].isnull().sum()

np.int64(0)

In [14]:
df['gdp_per_capita']=df['gdp_per_capita'].round(2)

In [15]:
df.head()

,economy,Country,year,gdp_per_capita,gdp_growth,fdi_inflows,unemployment,poverty_headcount,gini_index,life_expectancy,...,renewable_energy,forest_area,clean_water_access,female_labour,female_literacy,women_parliament,maternal_mortality,gender_parity,internet_users,sub_region
0,AFG,Afghanistan,2000,174.93,NaN,0.004828,7.897,NaN,NaN,55.005,...,45.0,1.852782,29.730966,14.294,NaN,NaN,1372.0,NaN,NaN,South Asia
1,AFG,Afghanistan,2001,138.71,-9.431974,0.024169,7.973,NaN,NaN,55.511,...,45.6,1.852782,29.762926,14.196,NaN,NaN,1311.0,0.00000,0.004723,South Asia
2,AFG,Afghanistan,2002,178.95,28.600001,1.306950,7.867,NaN,NaN,56.225,...,37.8,1.852782,31.836077,14.152,NaN,NaN,1263.0,NaN,0.004561,South Asia
3,AFG,Afghanistan,2003,198.87,8.832278,1.278493,7.844,NaN,NaN,57.171,...,36.7,1.852782,33.908629,14.154,NaN,NaN,1201.0,0.54426,0.087891,South Asia
4,AFG,Afghanistan,2004,221.76,1.414118,3.577104,7.794,NaN,NaN,57.810,...,44.2,1.852782,35.999355,14.205,NaN,NaN,1166.0,0.40582,0.105809,South Asia

In [16]:
df['gdp_growth'].isnull().sum()

np.int64(7)

In [17]:
df.dropna(subset='gdp_growth',inplace=True)

In [18]:
df['gdp_growth'].isnull().sum()

np.int64(0)

In [19]:
df['gdp_growth']=df['gdp_growth'].round(2)

In [20]:
df.shape

(1097, 28)

In [21]:
df['fdi_inflows'].isnull().sum()

np.int64(19)

In [22]:
df['fdi_inflows']=df.groupby('Country')['fdi_inflows'].transform(lambda x : x.fillna(x.median()))

In [23]:
df['fdi_inflows']=df['fdi_inflows'].round(2)

In [24]:
df.head()

,economy,Country,year,gdp_per_capita,gdp_growth,fdi_inflows,unemployment,poverty_headcount,gini_index,life_expectancy,...,renewable_energy,forest_area,clean_water_access,female_labour,female_literacy,women_parliament,maternal_mortality,gender_parity,internet_users,sub_region
1,AFG,Afghanistan,2001,138.71,-9.43,0.02,7.973,NaN,NaN,55.511,...,45.6,1.852782,29.762926,14.196,NaN,NaN,1311.0,0.00000,0.004723,South Asia
2,AFG,Afghanistan,2002,178.95,28.60,1.31,7.867,NaN,NaN,56.225,...,37.8,1.852782,31.836077,14.152,NaN,NaN,1263.0,NaN,0.004561,South Asia
3,AFG,Afghanistan,2003,198.87,8.83,1.28,7.844,NaN,NaN,57.171,...,36.7,1.852782,33.908629,14.154,NaN,NaN,1201.0,0.54426,0.087891,South Asia
4,AFG,Afghanistan,2004,221.76,1.41,3.58,7.794,NaN,NaN,57.810,...,44.2,1.852782,35.999355,14.205,NaN,NaN,1166.0,0.40582,0.105809,South Asia
5,AFG,Afghanistan,2005,254.18,11.23,4.37,7.878,NaN,NaN,58.247,...,33.9,1.852782,38.108054,14.302,NaN,27.309237,1108.0,0.54769,1.224150,South Asia

In [25]:
df['unemployment'].isnull().sum()

np.int64(1)

In [26]:
df.dropna(subset='unemployment',inplace = True)

In [27]:
df['poverty_headcount'].isna().sum()

np.int64(734)

In [28]:
df.drop(columns='poverty_headcount',inplace = True)

In [29]:
df['gini_index'].isna().sum()

np.int64(734)

In [30]:
df.drop(columns='gini_index',inplace = True)

In [31]:
df.columns

Index(['economy', 'Country', 'year', 'gdp_per_capita', 'gdp_growth',
       'fdi_inflows', 'unemployment', 'life_expectancy', 'infant_mortality',
       'hospital_beds', 'population', 'literacy_rate',
       'school_enrolment_primary', 'school_enrolment_secondary',
       'education_expenditure', 'electricity_access', 'renewable_energy',
       'forest_area', 'clean_water_access', 'female_labour', 'female_literacy',
       'women_parliament', 'maternal_mortality', 'gender_parity',
       'internet_users', 'sub_region'],
      dtype='object')

In [32]:
df.head()

,economy,Country,year,gdp_per_capita,gdp_growth,fdi_inflows,unemployment,life_expectancy,infant_mortality,hospital_beds,...,renewable_energy,forest_area,clean_water_access,female_labour,female_literacy,women_parliament,maternal_mortality,gender_parity,internet_users,sub_region
1,AFG,Afghanistan,2001,138.71,-9.43,0.02,7.973,55.511,107.0,NaN,...,45.6,1.852782,29.762926,14.196,NaN,NaN,1311.0,0.00000,0.004723,South Asia
2,AFG,Afghanistan,2002,178.95,28.60,1.31,7.867,56.225,103.8,NaN,...,37.8,1.852782,31.836077,14.152,NaN,NaN,1263.0,NaN,0.004561,South Asia
3,AFG,Afghanistan,2003,198.87,8.83,1.28,7.844,57.171,100.6,NaN,...,36.7,1.852782,33.908629,14.154,NaN,NaN,1201.0,0.54426,0.087891,South Asia
4,AFG,Afghanistan,2004,221.76,1.41,3.58,7.794,57.810,97.2,NaN,...,44.2,1.852782,35.999355,14.205,NaN,NaN,1166.0,0.40582,0.105809,South Asia
5,AFG,Afghanistan,2005,254.18,11.23,4.37,7.878,58.247,93.7,NaN,...,33.9,1.852782,38.108054,14.302,NaN,27.309237,1108.0,0.54769,1.224150,South Asia

In [33]:
df['life_expectancy'].isna().sum()

np.int64(0)

In [34]:
df['life_expectancy']=df['life_expectancy'].round(1)

In [35]:
df['infant_mortality'].isna().sum()

np.int64(0)

In [36]:
df['hospital_beds'].isna().sum()

np.int64(136)

In [37]:
df['hospital_beds'] = df.groupby('sub_region')['hospital_beds'].transform(
    lambda x: x.fillna(x.median())
)

In [38]:
df['population'].isna().sum()

np.int64(0)

In [39]:
(df['population']<0).sum()

np.int64(0)

In [40]:
df.isna().sum()

economy                         0
Country                         0
year                            0
gdp_per_capita                  0
gdp_growth                      0
fdi_inflows                     0
unemployment                    0
life_expectancy                 0
infant_mortality                0
hospital_beds                   0
population                      0
literacy_rate                 773
school_enrolment_primary      171
school_enrolment_secondary    279
education_expenditure         369
electricity_access              0
renewable_energy               84
forest_area                     0
clean_water_access              4
female_labour                   0
female_literacy               769
women_parliament               90
maternal_mortality              0
gender_parity                 459
internet_users                 34
sub_region                      0
dtype: int64

In [41]:
df.drop(columns='literacy_rate',inplace=True)

In [42]:
df['school_enrolment_primary'] = df.groupby('sub_region')['school_enrolment_primary'].transform(
    lambda x: x.fillna(x.median())
)
df['school_enrolment_secondary'] = df.groupby('sub_region')['school_enrolment_secondary'].transform(
    lambda x: x.fillna(x.median())
)

In [43]:
df.isna().sum()

economy                         0
Country                         0
year                            0
gdp_per_capita                  0
gdp_growth                      0
fdi_inflows                     0
unemployment                    0
life_expectancy                 0
infant_mortality                0
hospital_beds                   0
population                      0
school_enrolment_primary        0
school_enrolment_secondary      0
education_expenditure         369
electricity_access              0
renewable_energy               84
forest_area                     0
clean_water_access              4
female_labour                   0
female_literacy               769
women_parliament               90
maternal_mortality              0
gender_parity                 459
internet_users                 34
sub_region                      0
dtype: int64

In [44]:
(df['education_expenditure']<0).sum()

np.int64(0)

In [45]:
df['education_expenditure'] = df.groupby('sub_region')['education_expenditure'].transform(
    lambda x: x.fillna(x.median())
)

In [46]:
(df['electricity_access']<0).sum()

np.int64(0)

In [47]:
(df['renewable_energy']<0).sum()

np.int64(0)

In [48]:
df['renewable_energy'] = df.groupby('sub_region')['renewable_energy'].transform(
    lambda x: x.fillna(x.median())
)

In [49]:
print((df['forest_area']<0).sum())
print((df['clean_water_access']<0).sum())
print((df['gender_parity']<0).sum())
print((df['maternal_mortality']<0).sum())
print((df['internet_users']<0).sum())

0
0
0
0
0

In [50]:
df['clean_water_access'] = df.groupby('sub_region')['clean_water_access'].transform(
    lambda x: x.fillna(x.median())
)

In [51]:
df.drop(columns='female_literacy',inplace = True)

In [52]:
df['women_parliament'] = df.groupby('sub_region')['women_parliament'].transform(
    lambda x: x.fillna(x.median())
)

In [53]:
df.isnull().sum()

economy                         0
Country                         0
year                            0
gdp_per_capita                  0
gdp_growth                      0
fdi_inflows                     0
unemployment                    0
life_expectancy                 0
infant_mortality                0
hospital_beds                   0
population                      0
school_enrolment_primary        0
school_enrolment_secondary      0
education_expenditure           0
electricity_access              0
renewable_energy                0
forest_area                     0
clean_water_access              0
female_labour                   0
women_parliament                0
maternal_mortality              0
gender_parity                 459
internet_users                 34
sub_region                      0
dtype: int64

In [54]:
df['gender_parity'] = df.groupby('sub_region')['gender_parity'].transform(
    lambda x: x.fillna(x.median())
)

In [55]:
df['internet_users'] = df.groupby('sub_region')['internet_users'].transform(
    lambda x: x.fillna(x.median())
)

In [56]:
df.isnull().sum()

economy                       0
Country                       0
year                          0
gdp_per_capita                0
gdp_growth                    0
fdi_inflows                   0
unemployment                  0
life_expectancy               0
infant_mortality              0
hospital_beds                 0
population                    0
school_enrolment_primary      0
school_enrolment_secondary    0
education_expenditure         0
electricity_access            0
renewable_energy              0
forest_area                   0
clean_water_access            0
female_labour                 0
women_parliament              0
maternal_mortality            0
gender_parity                 0
internet_users                0
sub_region                    0
dtype: int64

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1096 entries, 1 to 1122
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   economy                     1096 non-null   object
 1   Country                     1096 non-null   object
 2   year                        1096 non-null   int64
 3   gdp_per_capita              1096 non-null   float64
 4   gdp_growth                  1096 non-null   float64
 5   fdi_inflows                 1096 non-null   float64
 6   unemployment                1096 non-null   float64
 7   life_expectancy             1096 non-null   float64
 8   infant_mortality            1096 non-null   float64
 9   hospital_beds               1096 non-null   float64
 10  population                  1096 non-null   float64
 11  school_enrolment_primary    1096 non-null   float64
 12  school_enrolment_secondary  1096 non-null   float64
 13  education_expenditure       1096 non-null   float64
 14  electricity_access          1096 non-null   float64
 15  renewable_energy            1096 non-null   float64
 16  forest_area                 1096 non-null   float64
 17  clean_water_access          1096 non-null   float64
 18  female_labour               1096 non-null   float64
 19  women_parliament            1096 non-null   float64
 20  maternal_mortality          1096 non-null   float64
 21  gender_parity               1096 non-null   float64
 22  internet_users              1096 non-null   float64
 23  sub_region                  1096 non-null   object
dtypes: float64(20), int64(1), object(3)
memory usage: 214.1+ KB

In [58]:
df.head()

,economy,Country,year,gdp_per_capita,gdp_growth,fdi_inflows,unemployment,life_expectancy,infant_mortality,hospital_beds,...,electricity_access,renewable_energy,forest_area,clean_water_access,female_labour,women_parliament,maternal_mortality,gender_parity,internet_users,sub_region
1,AFG,Afghanistan,2001,138.71,-9.43,0.02,7.973,55.5,107.0,1.66,...,9.3,45.6,1.852782,29.762926,14.196,11.808118,1311.0,0.000000,0.004723,South Asia
2,AFG,Afghanistan,2002,178.95,28.60,1.31,7.867,56.2,103.8,1.66,...,14.1,37.8,1.852782,31.836077,14.152,11.808118,1263.0,0.992585,0.004561,South Asia
3,AFG,Afghanistan,2003,198.87,8.83,1.28,7.844,57.2,100.6,1.66,...,19.0,36.7,1.852782,33.908629,14.154,11.808118,1201.0,0.544260,0.087891,South Asia
4,AFG,Afghanistan,2004,221.76,1.41,3.58,7.794,57.8,97.2,1.66,...,23.8,44.2,1.852782,35.999355,14.205,11.808118,1166.0,0.405820,0.105809,South Asia
5,AFG,Afghanistan,2005,254.18,11.23,4.37,7.878,58.2,93.7,1.66,...,28.7,33.9,1.852782,38.108054,14.302,27.309237,1108.0,0.547690,1.224150,South Asia

In [59]:
df['infant_mortality'].head()

1    107.0
2    103.8
3    100.6
4     97.2
5     93.7
Name: infant_mortality, dtype: float64

In [60]:
df.isnull().sum()

economy                       0
Country                       0
year                          0
gdp_per_capita                0
gdp_growth                    0
fdi_inflows                   0
unemployment                  0
life_expectancy               0
infant_mortality              0
hospital_beds                 0
population                    0
school_enrolment_primary      0
school_enrolment_secondary    0
education_expenditure         0
electricity_access            0
renewable_energy              0
forest_area                   0
clean_water_access            0
female_labour                 0
women_parliament              0
maternal_mortality            0
gender_parity                 0
internet_users                0
sub_region                    0
dtype: int64

In [61]:
df = df.round(3)

In [62]:
df.head()

,economy,Country,year,gdp_per_capita,gdp_growth,fdi_inflows,unemployment,life_expectancy,infant_mortality,hospital_beds,...,electricity_access,renewable_energy,forest_area,clean_water_access,female_labour,women_parliament,maternal_mortality,gender_parity,internet_users,sub_region
1,AFG,Afghanistan,2001,138.71,-9.43,0.02,7.973,55.5,107.0,1.66,...,9.3,45.6,1.853,29.763,14.196,11.808,1311.0,0.000,0.005,South Asia
2,AFG,Afghanistan,2002,178.95,28.60,1.31,7.867,56.2,103.8,1.66,...,14.1,37.8,1.853,31.836,14.152,11.808,1263.0,0.993,0.005,South Asia
3,AFG,Afghanistan,2003,198.87,8.83,1.28,7.844,57.2,100.6,1.66,...,19.0,36.7,1.853,33.909,14.154,11.808,1201.0,0.544,0.088,South Asia
4,AFG,Afghanistan,2004,221.76,1.41,3.58,7.794,57.8,97.2,1.66,...,23.8,44.2,1.853,35.999,14.205,11.808,1166.0,0.406,0.106,South Asia
5,AFG,Afghanistan,2005,254.18,11.23,4.37,7.878,58.2,93.7,1.66,...,28.7,33.9,1.853,38.108,14.302,27.309,1108.0,0.548,1.224,South Asia

In [63]:
df.columns.tolist()

['economy',
 'Country',
 'year',
 'gdp_per_capita',
 'gdp_growth',
 'fdi_inflows',
 'unemployment',
 'life_expectancy',
 'infant_mortality',
 'hospital_beds',
 'population',
 'school_enrolment_primary',
 'school_enrolment_secondary',
 'education_expenditure',
 'electricity_access',
 'renewable_energy',
 'forest_area',
 'clean_water_access',
 'female_labour',
 'women_parliament',
 'maternal_mortality',
 'gender_parity',
 'internet_users',
 'sub_region']

In [64]:
# Feature Engineering

In [65]:
pd.options.display.float_format='{:.2f}'.format

In [66]:
df['gdp_total']=df['gdp_per_capita'] * df['population']

In [67]:
df['gdp_total'].head()

1   2813636223.97
2   3825614037.15
3   4520921454.63
4   5224810631.04
5   6203152840.06
Name: gdp_total, dtype: float64

In [68]:
df['fdi_per_capita']=(df['fdi_inflows'] * 1_000_000_000) /df['population']
df['fdi_per_capita']

1        0.99
2       61.28
3       56.31
4      151.95
5      179.06
        ...
1118   -17.87
1119    -1.28
1120   -55.75
1121   -30.52
1122   -38.43
Name: fdi_per_capita, Length: 1096, dtype: float64

In [69]:
df['fdi_per_capita'].describe()

count     1096.00
mean      1277.34
std       3682.52
min     -12224.25
25%         12.39
50%        106.12
75%        929.98
max      40864.50
Name: fdi_per_capita, dtype: float64

In [70]:
print(df['fdi_inflows'].describe())
print(df['population'].describe())

count   1096.00
mean       3.72
std        5.63
min      -37.17
25%        0.75
50%        2.12
75%        4.67
max       55.07
Name: fdi_inflows, dtype: float64
count         1096.00
mean      92373972.67
std      266194489.98
min         282019.00
25%        4247435.75
50%       15851481.00
75%       51725669.75
max     1438069596.00
Name: population, dtype: float64

In [71]:
df['health_index']=(df['life_expectancy']/100) + (1/df['infant_mortality'])

In [72]:
df['education_index']=(df['school_enrolment_primary'] + df['school_enrolment_secondary'])/2

In [73]:
df['environment_index']=(df['renewable_energy'] + df['forest_area'] + df['clean_water_access'])/3

In [74]:
df['gender_index']=(df['female_labour'] + df['women_parliament'] + df['gender_parity']) / 3

In [75]:
df['development_index']=(df['electricity_access'] + df['clean_water_access']+df['internet_users']+df['education_index'])/4

In [76]:
df['development_category']=pd.cut(df['development_index'],
       bins=[0,30,50,70,90,100,110],
       labels=['Very Poor','Underdeveloped','Developing','Moderate','Developed','Highly Developed']
    )

In [77]:
df.head()

,economy,Country,year,gdp_per_capita,gdp_growth,fdi_inflows,unemployment,life_expectancy,infant_mortality,hospital_beds,...,internet_users,sub_region,gdp_total,fdi_per_capita,health_index,education_index,environment_index,gender_index,development_index,development_category
1,AFG,Afghanistan,2001,138.71,-9.43,0.02,7.97,55.50,107.00,1.66,...,0.01,South Asia,2813636223.97,0.99,0.56,18.09,25.74,8.67,14.29,Very Poor
2,AFG,Afghanistan,2002,178.95,28.60,1.31,7.87,56.20,103.80,1.66,...,0.01,South Asia,3825614037.15,61.28,0.57,66.41,23.83,8.98,28.09,Very Poor
3,AFG,Afghanistan,2003,198.87,8.83,1.28,7.84,57.20,100.60,1.66,...,0.09,South Asia,4520921454.63,56.31,0.58,54.65,24.15,8.84,26.91,Very Poor
4,AFG,Afghanistan,2004,221.76,1.41,3.58,7.79,57.80,97.20,1.66,...,0.11,South Asia,5224810631.04,151.95,0.59,62.34,27.35,8.81,30.56,Underdeveloped
5,AFG,Afghanistan,2005,254.18,11.23,4.37,7.88,58.20,93.70,1.66,...,1.22,South Asia,6203152840.06,179.06,0.59,59.89,24.62,14.05,31.98,Underdeveloped

In [78]:
df['life_expectancy_category']=pd.cut(df['life_expectancy'],
       bins=[0,50,60,70,80,90],
       labels=['Very Low','Low','Moderate','High','Very High']
      )

In [79]:
df['environment_category'] = pd.cut(
    df['environment_index'],
    bins=[0, 25, 40, 55, 70, 100],
    labels=['Critical', 'Poor', 'Moderate', 'Good', 'Excellent']
)

In [80]:
df['gdp_category'] = pd.cut(
    df['gdp_per_capita'],
    bins=[0, 1000, 5000, 15000, 40000, 200000],
    labels=['Low Income', 'Lower Middle', 'Upper Middle', 'High Income', 'Very High Income']
)

In [81]:
df['gender_category'] = pd.cut(
    df['gender_index'],
    bins=[0, 20, 40, 60, 80, 100],
    labels=['Very Poor', 'Poor', 'Moderate', 'Good', 'Excellent']
)

In [82]:
df.head()

,economy,Country,year,gdp_per_capita,gdp_growth,fdi_inflows,unemployment,life_expectancy,infant_mortality,hospital_beds,...,health_index,education_index,environment_index,gender_index,development_index,development_category,life_expectancy_category,environment_category,gdp_category,gender_category
1,AFG,Afghanistan,2001,138.71,-9.43,0.02,7.97,55.50,107.00,1.66,...,0.56,18.09,25.74,8.67,14.29,Very Poor,Low,Poor,Low Income,Very Poor
2,AFG,Afghanistan,2002,178.95,28.60,1.31,7.87,56.20,103.80,1.66,...,0.57,66.41,23.83,8.98,28.09,Very Poor,Low,Critical,Low Income,Very Poor
3,AFG,Afghanistan,2003,198.87,8.83,1.28,7.84,57.20,100.60,1.66,...,0.58,54.65,24.15,8.84,26.91,Very Poor,Low,Critical,Low Income,Very Poor
4,AFG,Afghanistan,2004,221.76,1.41,3.58,7.79,57.80,97.20,1.66,...,0.59,62.34,27.35,8.81,30.56,Underdeveloped,Low,Poor,Low Income,Very Poor
5,AFG,Afghanistan,2005,254.18,11.23,4.37,7.88,58.20,93.70,1.66,...,0.59,59.89,24.62,14.05,31.98,Underdeveloped,Low,Critical,Low Income,Very Poor

In [83]:
pd.crosstab(df['gdp_category'],df['development_category'])

development_category,Very Poor,Underdeveloped,Developing,Moderate,Developed,Highly Developed
gdp_category,,,,,,
Low Income,3,56,110,44,0,0
Lower Middle,0,5,123,281,48,0
Upper Middle,0,0,2,127,51,0
High Income,0,0,0,74,89,5
Very High Income,0,0,0,15,54,9

In [84]:
df.groupby('gdp_category', observed=True)['life_expectancy'].mean()

gdp_category
Low Income         65.21
Lower Middle       70.71
Upper Middle       74.59
High Income        78.89
Very High Income   81.02
Name: life_expectancy, dtype: float64

In [85]:
df.groupby('sub_region', observed=True)['development_category'].value_counts()

sub_region      development_category
Central Asia    Moderate                 83
                Developing               20
                Developed                17
                Very Poor                 0
                Underdeveloped            0
                Highly Developed          0
East Asia       Developed                47
                Moderate                 36
                Developing               13
                Very Poor                 0
                Underdeveloped            0
                Highly Developed          0
South Asia      Developing               99
                Moderate                 65
                Underdeveloped           14
                Developed                10
                Very Poor                 3
                Highly Developed          0
Southeast Asia  Moderate                116
                Developing               66
                Developed                46
                Underdeveloped           36
                Very Poor                 0
                Highly Developed          0
West Asia       Moderate                241
                Developed               122
                Developing               37
                Highly Developed         14
                Underdeveloped           11
                Very Poor                 0
Name: count, dtype: int64

In [86]:
df.groupby('gdp_category', observed=True)[['life_expectancy','education_index','environment_index','gender_index']].mean()

,life_expectancy,education_index,environment_index,gender_index
gdp_category,,,,
Low Income,65.21,81.87,47.12,18.90
Lower Middle,70.71,90.16,46.63,19.21
Upper Middle,74.59,92.30,40.10,18.85
High Income,78.89,98.36,41.93,18.70
Very High Income,81.02,98.60,39.81,23.69

In [87]:
df=df.round(3)

In [88]:
df=df.rename(columns={'Country':'country'})

In [89]:
df.dtypes

economy                         object
country                         object
year                             int64
gdp_per_capita                 float64
gdp_growth                     float64
fdi_inflows                    float64
unemployment                   float64
life_expectancy                float64
infant_mortality               float64
hospital_beds                  float64
population                     float64
school_enrolment_primary       float64
school_enrolment_secondary     float64
education_expenditure          float64
electricity_access             float64
renewable_energy               float64
forest_area                    float64
clean_water_access             float64
female_labour                  float64
women_parliament               float64
maternal_mortality             float64
gender_parity                  float64
internet_users                 float64
sub_region                      object
gdp_total                      float64
fdi_per_capita                 float64
health_index                   float64
education_index                float64
environment_index              float64
gender_index                   float64
development_index              float64
development_category          category
life_expectancy_category      category
environment_category          category
gdp_category                  category
gender_category               category
dtype: object

In [90]:
cat_cols = ['development_category','life_expectancy_category','environment_category','gdp_category','gender_category']
df[cat_cols]=df[cat_cols].astype(str)

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1096 entries, 1 to 1122
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   economy                     1096 non-null   object
 1   country                     1096 non-null   object
 2   year                        1096 non-null   int64
 3   gdp_per_capita              1096 non-null   float64
 4   gdp_growth                  1096 non-null   float64
 5   fdi_inflows                 1096 non-null   float64
 6   unemployment                1096 non-null   float64
 7   life_expectancy             1096 non-null   float64
 8   infant_mortality            1096 non-null   float64
 9   hospital_beds               1096 non-null   float64
 10  population                  1096 non-null   float64
 11  school_enrolment_primary    1096 non-null   float64
 12  school_enrolment_secondary  1096 non-null   float64
 13  education_expenditure       1096 non-null   float64
 14  electricity_access          1096 non-null   float64
 15  renewable_energy            1096 non-null   float64
 16  forest_area                 1096 non-null   float64
 17  clean_water_access          1096 non-null   float64
 18  female_labour               1096 non-null   float64
 19  women_parliament            1096 non-null   float64
 20  maternal_mortality          1096 non-null   float64
 21  gender_parity               1096 non-null   float64
 22  internet_users              1096 non-null   float64
 23  sub_region                  1096 non-null   object
 24  gdp_total                   1096 non-null   float64
 25  fdi_per_capita              1096 non-null   float64
 26  health_index                1096 non-null   float64
 27  education_index             1096 non-null   float64
 28  environment_index           1096 non-null   float64
 29  gender_index                1096 non-null   float64
 30  development_index           1096 non-null   float64
 31  development_category        1096 non-null   object
 32  life_expectancy_category    1096 non-null   object
 33  environment_category        1096 non-null   object
 34  gdp_category                1096 non-null   object
 35  gender_category             1096 non-null   object
dtypes: float64(27), int64(1), object(8)
memory usage: 316.8+ KB

In [92]:
df.to_csv('../Data/world_bank_cleaned.csv',index = False)

In [93]:
df.isna().sum()

economy                       0
country                       0
year                          0
gdp_per_capita                0
gdp_growth                    0
fdi_inflows                   0
unemployment                  0
life_expectancy               0
infant_mortality              0
hospital_beds                 0
population                    0
school_enrolment_primary      0
school_enrolment_secondary    0
education_expenditure         0
electricity_access            0
renewable_energy              0
forest_area                   0
clean_water_access            0
female_labour                 0
women_parliament              0
maternal_mortality            0
gender_parity                 0
internet_users                0
sub_region                    0
gdp_total                     0
fdi_per_capita                0
health_index                  0
education_index               0
environment_index             0
gender_index                  0
development_index             0
development_category          0
life_expectancy_category      0
environment_category          0
gdp_category                  0
gender_category               0
dtype: int64

In [94]:
df.head(10)

,economy,country,year,gdp_per_capita,gdp_growth,fdi_inflows,unemployment,life_expectancy,infant_mortality,hospital_beds,...,health_index,education_index,environment_index,gender_index,development_index,development_category,life_expectancy_category,environment_category,gdp_category,gender_category
1,AFG,Afghanistan,2001,138.71,-9.43,0.02,7.97,55.50,107.00,1.66,...,0.56,18.09,25.74,8.67,14.29,Very Poor,Low,Poor,Low Income,Very Poor
2,AFG,Afghanistan,2002,178.95,28.60,1.31,7.87,56.20,103.80,1.66,...,0.57,66.41,23.83,8.98,28.09,Very Poor,Low,Critical,Low Income,Very Poor
3,AFG,Afghanistan,2003,198.87,8.83,1.28,7.84,57.20,100.60,1.66,...,0.58,54.65,24.15,8.84,26.91,Very Poor,Low,Critical,Low Income,Very Poor
4,AFG,Afghanistan,2004,221.76,1.41,3.58,7.79,57.80,97.20,1.66,...,0.59,62.34,27.35,8.81,30.56,Underdeveloped,Low,Poor,Low Income,Very Poor
5,AFG,Afghanistan,2005,254.18,11.23,4.37,7.88,58.20,93.70,1.66,...,0.59,59.89,24.62,14.05,31.98,Underdeveloped,Low,Critical,Low Income,Very Poor
6,AFG,Afghanistan,2006,274.22,5.36,3.41,7.90,58.60,90.10,1.66,...,0.60,65.90,24.66,14.11,35.43,Underdeveloped,Low,Critical,Low Income,Very Poor
7,AFG,Afghanistan,2007,376.22,13.83,1.94,7.84,59.00,86.70,1.66,...,0.60,64.07,24.36,14.31,36.70,Underdeveloped,Low,Critical,Low Income,Very Poor
8,AFG,Afghanistan,2008,381.73,3.92,0.46,7.88,59.70,83.30,1.66,...,0.61,71.69,22.57,14.40,40.15,Underdeveloped,Low,Critical,Low Income,Very Poor
9,AFG,Afghanistan,2009,452.05,21.39,0.45,7.81,60.20,80.00,1.66,...,0.61,72.00,21.75,14.39,42.69,Underdeveloped,Moderate,Critical,Low Income,Very Poor
10,AFG,Afghanistan,2010,560.62,14.36,1.20,7.81,60.70,76.90,1.66,...,0.62,76.96,22.06,14.64,43.20,Underdeveloped,Moderate,Critical,Low Income,Very Poor